### PR TITLE
General Gun Ammo and Calibre Fixes

### PR DESCRIPTION
**Pull request by Ophanimdev**
This PR does the Following:

- Makes it so guns under _Cresent actually represent their ammo calibres in their name and description if present.
- Removes empty mags from lathe recipes because no one actually wants to make empty mags because you can't make boxes of loose ammo anyway.
- Rebalances bullet damage so small calibres don't do the same exact amount of damage as RIFLES!!!
- ^ Means shotgun slugs and rifle rounds pack quite the punch.
- Makes the Communard Full Auto shotgun's firerate slightly better. 
- Pistols don't have the same firerates as rifles anymore.
- Revolvers buffed as a concession to their low firerate.
- Removes practice ammo from the lathe recipes.

### CODE REVIEW

**Comment by somalian-negus** [comment]
+1

**Comment by a-person5660** [comment]
rename the bullets to their IRL counterparts over SS14s backward logic.

**Comment by Ophanimdev** [comment]
> rename the bullets to their IRL counterparts over SS14s backward logic.

I'm not a gun nut, and the actual problem's that all the guns use SS14's vanilla bullets and mags. I can't make new mags or rounds because I can't actually add sprites to the codebase, nor do I want to reuse existing sprites since I think bullets and magazines should be identifiable at a glance. At least this way we're not loading .20 mags into 7.62 chambers anymore.

**Comment by JoeHammad1844** [comment]
10 damage pistols are cringe

**Comment by JoeHammad1844** [comment]
I think leaving 35 auto at 21 but buffing the rifle cartridges is enough

**Comment by Ophanimdev** [comment]
As seen in the commit history - I've added some entities for the following calibres:

- 9x19 Parabellum
- .30 (7.62)
- .50 BMG 

None of the example magazines which make use of these calibres actually go into any guns at the moment. 
This is because I can't actually give them sprites and I don't want them to use the same sprites as the other mags, because I want them to be identifiable at a glance.

**Comment by ilikeships** [comment]
this seems interesting, gonna look into it near Friday and maybe test it a little on my dev repo and get back to you

**Comment by Leviathan21** [comment]
smg bullet deals 10 dmg LMAO

**Pull request merged**
