### PR TITLE
Removes Felinids

### PR DESCRIPTION
**Pull request by Ophanimdev**
Saw this in the 'rotcord.
Don't want any more of this. 
image

### CODE REVIEW

**Comment by somalian-negus** [comment]
Defaulting the height to the regular will suffice, so as not to provoke the donator cabal. 
Murder of Felinids is a core function of the game.

**Comment by somalian-negus** [comment]
Defaulting their height to the human regular will suffice, murder of felinids is a core function of the game.

**Comment by MLGTASTICa** [comment]
Removal of SS13 soul.. -1 On this. Waiting on aisha's feedback.

**Comment by Ophanimdev** [comment]
> Removal of SS13 soul.. -1 On this. Waiting on aisha's feedback.

image

**Comment by Leviathan21** [comment]
hell nah

**Comment by MarioDeez** [comment]
Holy based???? We need this. NO MORE FELINID SEX SLAVE RP

**Comment by SixplyDev** [comment]
Pls remove

**Comment by Elijahrane** [comment]
I recommend https://github.com/Goob-Station/Goob-Station/pull/1081

**Pull request closed without merging**
