### PR TITLE
Ammo model rework

### PR DESCRIPTION
**Pull request by ninruB**
!!!HUGE FUCKING STUB ALARM!!!
THIS SHIT IS NOT FINISHED CONCEPTUALLY OR CRUD-WISE
!!!HUGE FUCKING STUB ALARM!!!

How ammo is currently sorted, assigned and balanced is a complete fucking nightmare and does not make sense in the slightest, this PR tries to standardize ammo into 6 categories:

Pistol ammo
Revolver ammo (magnum, will rename eventually)
SMG ammo
Rifle ammo
Sniper ammo
Shotgun shells

Nuke caseless ammo, merge light and heavy rifle calibers (until balancing issues pop up but then its easy to fix)

+Subvariants like incendiary, uranium, practice, rubber, buckshot, slug, etc. you get the idea

What this hopefully achieves is clarity and makes balancing less CBT, there is no reason why SMG and pistol balance should rely on the exact same bullet prototype, why the fuck do we have prototypes for guns or ammo that literally aren't in the game.

### CODE REVIEW

**Comment by a-person5660** [comment]
boooring, use actual ammo calibers :trollface:

**Comment by ninruB** [comment]
> boooring, use actual ammo calibers :trollface:

if you're willing to compile actual calibers for me that will replace the 6 boring categories ill add it despite preferring videogameisms

**Comment by ninruB** [comment]
@MLGTASTICa does this have your blessing as a concept or do we stick with the erisoid ammo

**Comment by ninruB** [comment]
this is too much coal for my weak and fragile back im postponing this until la rebazo

**Pull request closed without merging**
