### PR TITLE
Remove speed modifier from voidsuits/NON space suits(NO VACUUM PROTECTION)

### PR DESCRIPTION
**Pull request by wabash1**
Remove speed modifier from voidsuits. buff speed of nonspace suits to 1 from .9, some suits downstream appear to have their own modifiers.

### CODE REVIEW

**Comment by a-person5660** [comment]
1 is base move speed so you could just remove it. 0.9 is a 10% speed debuff.

**Comment by wabash1** [comment]
> 1 is base move speed so you could just remove it. 0.9 is a 10% speed debuff.

I was wondering how that would handle as this is the parent and there are children that reference a 1 move speed to the parent. I was thinking it might be cleaner to just straight up remove it and then go to the others and remove the 1 from those too.

**Comment by wabash1** [comment]
> 1 is base move speed so you could just remove it. 0.9 is a 10% speed debuff.

Updated changes as requested

**Comment by MLGTASTICa** [comment]
No, voidsuits and space suits need to remain slow to give a advantage to using normal armor.

**Pull request closed without merging**
