### PR TITLE
Drugs are Worth Using Now

### PR DESCRIPTION
**Pull request by Ophanimdev**
Previously, drugs were kind of awful. You'd go through all the process of finding a reputable dealer, getting it mixed up, paying thousands in convenience fees, and for what? A sub-par, WEAKER omnizine? 

Not anymore. Drugs are good and far better for those oozing leisions than any 'legal' medicine.
Their chemistry's been altered and now they're somewhat specialized. Here's the rundown.

Crash
- Faustian deal
- You get: Insane speed beyond all other drugs, stun immunity
- But: You have a 20% chance to vomit every time you metabolize it. You give up your sanity, and you find it a little hard to breathe when you're taking Crash.

Exile
- Gives you great speed (Much less than crash)
- Tiny passive healing if you're under 50 damage
- Hallucinations and crackspeech

Kaiser
- Unparaleled healing capabilities
- Nigh-immortal while it sits unmetabolized.
- No downsides, it's yours, friend.

Mechanites
- Heals brute damage slightly better than bicaridine
- Seals bleeding in record time
- Keeps you awake if you're narcoleptic for some reason. (Explain this, developers?)

Bloodeye
- Lets you spacewalk without a suit
- No downsides.

A lot of these drugs have lethal side effects when you try to dose them all at the same time.

These changes should make people addicted to these drugs oocly as well as ICly.

Fulfills: https://discord.com/channels/1194256269792510022/1310650773662728203/1310650773662728203

### CODE REVIEW

**Comment by a-person5660** [comment]
crash having a 20% chance to vomit every half a second might as well be 100% since the stim contains so much of it, vomiting also slows you down by a lot which defeats the point of it. change it from 20% chance to vomit to something like 20% chance to scream so your always giving away your location.

make mechanites work on the dead too since that would fit in lore,

bloodeye kinda seems a bit useless since hardsuits are so plentiful, maybe make it a budget kaiser, stop bleeds and make you scream. a fun OD so it cant be spammed would be increasing the metabolisers temperature so if they take too many they literally burn themselves to death.

**Comment by MLGTASTICa** [comment]
-1 Far too extreme. Im not willing to have healing chems with over -12  healing per tick unless you also make them last less than 5-4 healing ticks

**Comment by a-person5660** [comment]
> -1 Far too extreme. Im not willing to have healing chems with over -12 healing per tick unless you also make them last less than 5-4 healing ticks

do you mean quadruple metabolism and quadruple healing so it runs out quicker?

**Comment by a-person5660** [comment]
also make crash reduce stun time

**Comment by Ophanimdev** [comment]
> also make crash reduce stun time

It already does this.

**Comment by a-person5660** [comment]
> > also make crash reduce stun time
> 
> It already does this.

forgor :trollface:

**Comment by Ophanimdev** [comment]
I think drugs should be good so that people buy them.

**Comment by MLGTASTICa** [comment]
> I think drugs should be good so that people buy them.

Drugs shouldn't make you invincible to bullet damage.

**Comment by Ophanimdev** [comment]
I can't add any special health effects, I have to make do with what I've got. 
But I am welcome to hear how you might improve drugs yourself, since as it is, they're still not good enough for anyone to care about buying them since actual medicine's still much easier to obtain.

**Comment by alpharius405** [comment]
+1 Finally making drugs more useful and with the other Antiquarian buff, hopefully people will want to produce drugs now

**Comment by a-person5660** [comment]
btw i made a PR thats just this but revived and with good changes. #40

**Comment by a-person5660** [comment]
now that #40 is merged this should be closed :trollface:

**Comment by Ophanimdev** [comment]
> now that #40 is merged this should be closed :trollface:

You are a frog in a well.

**Comment by MLGTASTICa** [comment]
I merged #40 , if that is not enough feel free to open another PR to change them even more.

**Pull request closed without merging**
